name: agi_events
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7 # Widget for SVG assets
  # Firebase
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4 # Realtime Database
  # QR Code Scanner
  mobile_scanner: ^3.3.0
  # Export & Share CSV
  csv: ^5.0.2
  device_info_plus: ^9.0.3
  path_provider: ^2.0.15
  share_plus: ^7.1.0
  # State Management
  flutter_riverpod: ^2.3.6
  # Date formatting
  intl: ^0.18.1
  # Local database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  auto_animated: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # # Local database
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/