name: agi_events
description: A Flutter app for exhibitors in AGI Events
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  # Widget for SVG assets
  flutter_svg: ^2.0.7
  # Firebase & Realtime Database
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  # QR Code Scanner
  mobile_scanner: ^3.3.0
  # Export & Share CSV
  csv: ^5.0.2
  device_info_plus: ^9.0.3
  path_provider: ^2.0.15
  share_plus: ^7.1.0
  # State Management
  flutter_riverpod: ^2.3.6
  # Date Formatting
  intl: ^0.18.1
  # Local Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  # Animate SliverGrids [EventsPage]
  auto_animated: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Local Database [Tools]
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  # Command-line tool for updating Android & iOS launcher icons
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/images/app/app-icon.png"
  android: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app/app-icon.png"
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/app/
    - assets/images/events/