// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTJTtgwxY-BqmjLjHKQTaiDFVAagPmfsk',
    appId: '1:17995575553:android:41c7e9315cdee752b3ab00',
    messagingSenderId: '17995575553',
    projectId: 'agi-sandbox-90b17',
    databaseURL: 'https://agi-sandbox-90b17-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'agi-sandbox-90b17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkKSZdXgVDxoYYzuXZU6rrn9J1_KaFL5U',
    appId: '1:17995575553:ios:ba1b7cd49dbe9fa4b3ab00',
    messagingSenderId: '17995575553',
    projectId: 'agi-sandbox-90b17',
    databaseURL: 'https://agi-sandbox-90b17-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'agi-sandbox-90b17.appspot.com',
    iosClientId: '17995575553-o1igohqatgeu4jbnb0771crbbfe4nogu.apps.googleusercontent.com',
    iosBundleId: 'tech.neurothrone.agiEvents',
  );
}
