// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYNUS0ZVkZZ0oxJLsHxjKoHHg_5duEzWk',
    appId: '1:769821380069:android:99288e2741221f6a9b330c',
    messagingSenderId: '769821380069',
    projectId: 'devops-registrering',
    databaseURL: 'https://devops-registrering-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'devops-registrering.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGxwW1jDoXb4jtjN66vd_OW5MawwLThAE',
    appId: '1:769821380069:ios:59c437935414e0249b330c',
    messagingSenderId: '769821380069',
    projectId: 'devops-registrering',
    databaseURL: 'https://devops-registrering-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'devops-registrering.appspot.com',
    iosClientId: '769821380069-knoochc0gcdgqod52opiik1ks49c5knh.apps.googleusercontent.com',
    iosBundleId: 'com.agi.EmJo-Exhibitor',
  );
}
